import Image from "next/image";
import Link from "next/link";
import type { CompanyProfile } from "@/data/company";
import { getGeneralWhatsAppUrl } from "@/lib/contact";

export function AboutPageContent({ company }: { company: CompanyProfile }) {
  return <main className="bg-warm-bg">
    <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 sm:py-16 lg:px-8">
      <div className="grid items-start gap-10 lg:grid-cols-[0.9fr_1.1fr]">
        <div className="overflow-hidden rounded-card border border-warm-border bg-warm-surface shadow-card">
          <div className="relative aspect-[4/3]"><Image src={company.media?.aboutUrl || "/images/travel-team.jpg"} alt="Tim Risalah Madina Tour" fill sizes="(max-width: 1024px) 100vw, 40vw" className="object-cover" /></div>
          <div className="p-5"><p className="text-sm font-semibold text-teal-primary">{company.legalName}</p><p className="mt-1 text-sm text-slate-muted">{company.address}</p></div>
        </div>
        <div>
          <h1 className="font-serif text-4xl font-bold leading-tight text-teal-primary sm:text-5xl">Tentang {company.brandName}</h1>
          <p className="mt-5 max-w-2xl text-base leading-7 text-slate-body">{company.brandName} adalah brand dari {company.legalName}. Kami melayani Umroh Reguler dan Plus, Haji Khusus, Badal Haji dan Umroh, serta perjalanan domestik dan internasional.</p>
          <div className="mt-8 grid gap-3 sm:grid-cols-2"><div className="border-y border-warm-border py-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-muted">Layanan</p><p className="mt-2 text-sm leading-6 text-slate-body">{company.services.join(" · ")}</p></div><div className="border-y border-warm-border py-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-muted">Destinasi</p><p className="mt-2 text-sm leading-6 text-slate-body">{company.destinations.join(" · ")}</p></div></div>
          <h2 className="mt-12 font-serif text-2xl font-bold text-teal-primary">Tim kepemimpinan</h2>
          <div className="mt-4 grid gap-4 sm:grid-cols-3">{company.leaders.map((leader) => <article key={leader.name} className="overflow-hidden rounded-card border border-warm-border bg-warm-surface"><div className="relative aspect-square bg-teal-primary/10">{leader.imageUrl ? <Image src={leader.imageUrl} alt={`Foto ${leader.name}`} fill sizes="(max-width: 640px) 100vw, 33vw" className="object-cover" /> : <div className="flex h-full items-center justify-center font-serif text-3xl font-bold text-teal-primary">{leader.name.split(" ").slice(0, 2).map((part) => part[0]).join("")}</div>}</div><div className="p-4"><h3 className="text-base font-bold text-teal-primary">{leader.name}</h3><p className="mt-1 text-sm font-semibold text-gold-hover">{leader.role}</p><p className="mt-2 text-sm leading-6 text-slate-body">{leader.description}</p></div></article>)}</div>
        </div>
      </div>
      <div className="mt-14 flex flex-col items-start justify-between gap-4 border-t border-warm-border pt-7 sm:flex-row sm:items-center"><p className="text-sm text-slate-muted">Ingin memulai dari jadwal yang tersedia?</p><Link href="/umroh" className="min-h-11 rounded-button bg-teal-primary px-5 py-3 text-sm font-bold text-white hover:bg-teal-900">Lihat paket Umroh</Link></div>
    </div>
  </main>;
}

export function LegalityPageContent({ company }: { company: CompanyProfile }) {
  const rows = [["Badan usaha", company.legalName], ["SK PPIU Kemenag RI", company.legal.ppiu], ["SK PIHK", company.legal.pihk], ["Akte pendirian", company.legal.deed], ["SK Kemenkumham", company.legal.kemenkumham], ["NIB", company.legal.nib], ["NPWP", company.legal.npwp], ["Sertifikat", `${company.certification.number} · Akreditasi ${company.certification.accreditation}`], ["Masa berlaku", company.certification.validUntil]];
  return <main className="bg-warm-bg"><div className="mx-auto max-w-5xl px-4 py-12 sm:px-6 sm:py-16 lg:px-8"><h1 className="font-serif text-4xl font-bold text-teal-primary sm:text-5xl">Legalitas &amp; rekening resmi</h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-body">Baca data legalitas sebelum melakukan pembayaran. Cocokkan nama badan usaha dan rekening penerima dengan informasi di bawah ini.</p><div className="mt-10 overflow-hidden rounded-card border border-warm-border bg-warm-surface shadow-card"><dl>{rows.map(([label, value]) => <div key={label} className="grid gap-1 border-b border-warm-border p-5 last:border-0 sm:grid-cols-[220px_1fr] sm:gap-8"><dt className="text-xs font-bold uppercase tracking-wider text-slate-muted">{label}</dt><dd className="text-sm font-semibold leading-6 text-teal-primary">{value}</dd></div>)}</dl></div><div className="mt-8 grid gap-4 sm:grid-cols-3">{company.bankAccounts.map((account) => <div key={account.bank} className="border-y border-warm-border py-4"><p className="text-sm font-bold text-teal-primary">{account.bank}</p><p className="mt-2 font-mono text-base text-slate-body">{account.account}</p><p className="mt-1 text-xs text-slate-muted">Atas nama Risalah Madina</p></div>)}</div><div className="mt-12 rounded-card bg-teal-primary p-6 text-white sm:p-8"><h2 className="font-serif text-2xl font-bold">Perlu konfirmasi sebelum transfer?</h2><p className="mt-2 max-w-xl text-sm leading-6 text-white/75">Hubungi kanal resmi agar nama penerima, jadwal, dan komponen biaya dapat dicocokkan.</p><a href={getGeneralWhatsAppUrl(company.phone)} target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex min-h-11 items-center rounded-button bg-gold-accent px-5 py-3 text-sm font-bold text-slate-dark">Konsultasi via WhatsApp</a></div></div></main>;
}

export function DocumentationPageContent({ company }: { company: CompanyProfile }) {
  const documentationUrls = company.media?.documentationUrls || [];
  const items = [{ src: documentationUrls[0] || "/images/kaaba-courtyard.png", alt: "Masjidil Haram", title: "Masjidil Haram", caption: "Dokumentasi perjalanan ibadah" }, { src: documentationUrls[1] || "/images/madina-pilgrims.webp", alt: "Jemaah di Madinah", title: "Madinah", caption: "Pendampingan jemaah di kota Nabi" }, { src: documentationUrls[2] || "/images/travel-team.jpg", alt: "Tim travel", title: "Tim pendamping", caption: "Persiapan dan pendampingan perjalanan" }];
  return <main id="dokumentasi" className="bg-warm-bg"><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 sm:py-16 lg:px-8"><h1 className="font-serif text-4xl font-bold text-teal-primary sm:text-5xl">Dokumentasi perjalanan</h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-body">Lihat suasana tempat dan tim yang menjadi bagian dari perjalanan bersama Risalah Madina Tour.</p><div className="mt-10 grid gap-5 md:grid-cols-3">{items.map((item) => <figure key={item.title} className="overflow-hidden rounded-card border border-warm-border bg-warm-surface shadow-card"><div className="relative aspect-[4/3]"><Image src={item.src} alt={item.alt} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover" /></div><figcaption className="p-5"><h2 className="font-serif text-xl font-bold text-teal-primary">{item.title}</h2><p className="mt-1 text-sm text-slate-muted">{item.caption}</p></figcaption></figure>)}</div><p className="mt-8 text-xs italic text-slate-muted">Dokumentasi akan diperbarui sesuai izin publikasi dan keberangkatan yang tersedia.</p></div></main>;
}

export function HowItWorksSection({ company }: { company: CompanyProfile }) {
  const steps = [["Pilih paket", "Bandingkan tanggal, hotel, maskapai, dan tipe kamar."], ["Konsultasi", "Tanyakan ketersediaan serta kecocokan paket untuk keluarga."], ["Dokumen & manasik", "Lengkapi persyaratan dan ikuti persiapan keberangkatan."], ["Berangkat", "Ikuti pendampingan sesuai jadwal perjalanan." ]];
  return <section className="border-t border-warm-border bg-warm-surface py-12 sm:py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="font-serif text-3xl font-bold text-teal-primary">Cara berangkat</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate-muted">Satu alur singkat dari memilih jadwal sampai persiapan perjalanan.</p></div><Link href="/faq" className="text-sm font-bold text-teal-primary hover:text-gold-hover">Pelajari proses lengkap →</Link></div><div className="mt-8 grid gap-6 md:grid-cols-4">{steps.map(([title, description], index) => <div key={title} className="border-t border-teal-primary pt-4"><p className="font-mono text-xs font-bold text-gold-hover">{String(index + 1).padStart(2, "0")}</p><h3 className="mt-3 text-base font-bold text-teal-primary">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-body">{description}</p></div>)}</div><a href={getGeneralWhatsAppUrl(company.phone)} target="_blank" rel="noopener noreferrer" className="mt-8 inline-flex min-h-11 items-center rounded-button border border-teal-primary px-5 py-3 text-sm font-bold text-teal-primary hover:bg-teal-primary hover:text-white">Konsultasi alur perjalanan</a></div></section>;
}

export function LegalityTeaser({ company }: { company: CompanyProfile }) {
  return <section className="border-t border-warm-border bg-warm-bg py-12 sm:py-16"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h2 className="font-serif text-3xl font-bold text-teal-primary">Bukti yang bisa diperiksa</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-muted">Data legalitas utama tersedia terbuka, bersama alamat kantor dan rekening pembayaran resmi.</p></div><Link href="/legalitas" className="text-sm font-bold text-teal-primary hover:text-gold-hover">Lihat legalitas lengkap →</Link></div><div className="mt-8 grid gap-6 sm:grid-cols-3">{[["SK PPIU", company.legal.ppiu], ["SK PIHK", company.legal.pihk], ["Sertifikasi", `${company.certification.number} · Akreditasi ${company.certification.accreditation}`]].map(([label, value]) => <div key={label} className="border-y border-warm-border py-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-muted">{label}</p><p className="mt-2 text-sm font-bold text-teal-primary">{value}</p></div>)}</div></div></section>;
}

export function HajiOverviewSection({ company }: { company: CompanyProfile }) {
  return <section className="border-b border-warm-border bg-warm-surface"><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 sm:py-14 lg:px-8"><div className="grid gap-8 lg:grid-cols-[1.2fr_0.8fr] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-gold-hover">Haji Khusus</p><h2 className="mt-2 max-w-3xl font-serif text-4xl font-bold leading-tight text-teal-primary sm:text-5xl">Rencanakan Haji dengan informasi yang bisa diperiksa</h2><p className="mt-4 max-w-2xl text-base leading-7 text-slate-body">Pelajari prosedur, dokumen, pilihan pembiayaan, dan jadwal program sebelum berkonsultasi. Setiap kuota dan nilai transaksi tetap perlu dikonfirmasi berdasarkan keberangkatan.</p></div><div className="border-l-2 border-gold-accent pl-5"><p className="text-sm font-bold text-teal-primary">Data program yang tersedia</p><p className="mt-2 text-sm leading-6 text-slate-body">Profil layanan mencantumkan DP Haji {company.financing.hajjDp}, tenor tabungan 72 bulan, dan estimasi masa tunggu 6 tahun.</p><div className="mt-4 flex flex-wrap gap-3"><Link href="/pembiayaan" className="text-sm font-bold text-teal-primary hover:text-gold-hover">Lihat skema pembiayaan →</Link><a href={getGeneralWhatsAppUrl(company.phone)} target="_blank" rel="noopener noreferrer" className="text-sm font-bold text-teal-primary hover:text-gold-hover">Konsultasi Haji →</a></div></div></div></div></section>;
}
