-- Risalah Madina Tour CMS: jalankan seluruh file ini di Supabase SQL Editor.
-- Setelah itu buat user melalui Authentication > Users, lalu masukkan user tersebut
-- ke cms_members dengan role admin/editor/viewer.

create table if not exists public.cms_members (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'viewer' check (role in ('admin', 'editor', 'viewer')),
  created_at timestamptz not null default now()
);

create table if not exists public.cms_site_data (
  id boolean primary key default true check (id = true),
  company jsonb not null default '{}'::jsonb,
  packages jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.cms_audit_log (
  id bigint generated by default as identity primary key,
  action text not null check (action in ('insert', 'update', 'delete')),
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now(),
  snapshot jsonb
);

alter table public.cms_members enable row level security;
alter table public.cms_site_data enable row level security;
alter table public.cms_audit_log enable row level security;

create or replace function public.is_cms_editor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.cms_members
    where user_id = auth.uid() and role in ('admin', 'editor')
  );
$$;

create or replace function public.is_cms_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.cms_members
    where user_id = auth.uid() and role = 'admin'
  );
$$;

drop policy if exists "members can see own membership" on public.cms_members;
create policy "members can see own membership"
  on public.cms_members for select
  to authenticated
  using (user_id = auth.uid());

drop policy if exists "public can read site data" on public.cms_site_data;
create policy "public can read site data"
  on public.cms_site_data for select
  to anon, authenticated
  using (true);

drop policy if exists "editors can insert site data" on public.cms_site_data;
create policy "editors can insert site data"
  on public.cms_site_data for insert
  to authenticated
  with check (public.is_cms_editor());

drop policy if exists "editors can update site data" on public.cms_site_data;
create policy "editors can update site data"
  on public.cms_site_data for update
  to authenticated
  using (public.is_cms_editor())
  with check (public.is_cms_editor());

drop policy if exists "admins can delete site data" on public.cms_site_data;
create policy "admins can delete site data"
  on public.cms_site_data for delete
  to authenticated
  using (public.is_cms_admin());

drop policy if exists "admins can read audit log" on public.cms_audit_log;
create policy "admins can read audit log"
  on public.cms_audit_log for select
  to authenticated
  using (public.is_cms_admin());

create or replace function public.log_cms_site_data_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.cms_audit_log(action, changed_by, snapshot)
  values (
    lower(tg_op),
    auth.uid(),
    case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end
  );
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

drop trigger if exists cms_site_data_audit on public.cms_site_data;
create trigger cms_site_data_audit
after insert or update or delete on public.cms_site_data
for each row execute function public.log_cms_site_data_change();

-- Tidak ada data dummy yang ditanam oleh migration ini.
-- Login ke /admin, lalu Simpan perubahan untuk mengunggah seed profil dan paket
-- yang sudah tersedia di project ke row cms_site_data.
